declare module 'eslint'
declare module 'eslint-config-prettier'
declare module 'eslint-plugin-prettier'
declare module 'eslint-plugin-react'
declare module 'eslint-plugin-react-hooks'
declare module 'eslint-plugin-react-refresh'
